var terms = [
  "Fahrrad auf der Bühne",
  "Kartenanwendung",
  "Jovel",
  "Aasee",
  "Veranstaltungen",
  "KI",
  "Machine Learning",
  "Bus",
  "Alternate Reality",
  "Nachhaltigkeit",
  "Lewe",
  "Ehrenamt",
  "Crowdsourcing",
  "LoRa",
  "Leeze",
  "Web-App",
  "Parken",
  "Vorhersage",
  "Chatbot",
  "Behördenformular",
  "Tourismus",
  "Mobilität",
  "Klima",
  "Innovation",
  "3D",
  "Open Data",
  "Eltern",
  "Familien",
  "Solar",
  "Blutspende",
  "Comic Sans",
  "Vielen Dank für eure Aufmerksamkeit",
  "Münster im Namen",
  "LED-Panel",
  "3D-Druck",
  "Lasercutter",
  "Masematte",
  "I18N",
  "Bilderkennung",
  "Geo-Tracking",
  "Event App",
  "Lasercutter",
  "Ampeldaten",
  "Blockchain",
  "Tinder",
  "NFTs",
  "Fachkräftemangel",
  "Impact",
  "Demo schlägt fehl",
  "Schofel",
  "Personas",
  "Bürgerservice",
  "Wortwitz",
  "Open Source",
  "AI",
  "KI und AI in einem Satz",
  "ChatGPT",
  "Sprachmodell",
  "LLM",
  "Sicherheit",
  "Integration",
  "Verwaltung",
  "Datenbank",
  "Data Lake",
  "Big Data",
  "Cloud",
  "Demokratie",
  "Ratsinformationssystem",
];
